dist: xenial
addons:
  apt:
    packages:
    - hugo
before_install:
- openssl aes-256-cbc -K $encrypted_f0193fe2c4ee_key -iv $encrypted_f0193fe2c4ee_iv
  -in id_rsa.enc -out id_rsa -d
script:
  - hugo version
  - hugo
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public/ lijinglin@lijinglin.dev:/usr/share/nginx/html
  on:
    branch: master
