dist: xenial
addons:
  ssh_known_hosts:
  - lijinglin.dev
  snaps:
  - hugo
install:
  - hugo version
  - hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_f0193fe2c4ee_key -iv $encrypted_f0193fe2c4ee_iv
  -in id_rsa.enc -out id_rsa -d
- ssh-add id_rsa
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public/ lijinglin@lijinglin.dev:/usr/share/nginx/html
  on:
    branch: master
